### PR TITLE
'Attempt to read protected memory'

### PR DESCRIPTION
**Pull request by SteveWilkes**
Added test throws exception when func is invoked: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt'.

### CODE REVIEW

**Comment by jogibear9988** [comment]
Your Lambda Expression in the Test could also not be compiled by MS compiler!

**Comment by SteveWilkes** [comment]
Really? Oh dear, sorry about that - I'll fix it and update.

**Comment by SteveWilkes** [comment]
Fixed - the lambda compiles and executes with the MS compiler, compiles and throws 'Attempted to read or write protected memory' with FEC.

Sorry about that! :)

**Comment by jogibear9988** [comment]
it's fixed in my pull req

**Comment by dadhi** [comment]
Closing, as the work merged in #145

**Pull request closed without merging**
