### PR TITLE
V3 version

### PR DESCRIPTION
**Pull request by dadhi**

### CODE REVIEW

**Comment by jogibear9988** [comment]
I've updated our linq2db branch supporting alternative expression compiler, to use the v3 brach: https://github.com/linq2db/linq2db/pull/1277

But there are still some cases wich need to be fixed. I did not dig deeper into them at the moment.

**Comment by jogibear9988** [comment]
For example this fails:

	.Lambda #Lambda1<System.Func`2[System.Nullable`1[Tests.Common.ConvertTests+Enum15],System.Nullable`1[System.Int32]]>(System.Nullable`1[Tests.Common.ConvertTests+Enum15] $p)
	{
		.If (
			$p.HasValue
		) {
			.Switch ((Tests.Common.ConvertTests+Enum15)$p) {
			.Case (.Constant<Tests.Common.ConvertTests+Enum15>(AA)):
					.Constant<System.Nullable`1[System.Int32]>(10)
			.Case (.Constant<Tests.Common.ConvertTests+Enum15>(BB)):
					.Constant<System.Nullable`1[System.Int32]>(20)
			.Default:
					(System.Nullable`1[System.Int32]).Call LinqToDB.Common.ConvertBuilder.ConvertDefault(
						(System.Object)((Tests.Common.ConvertTests+Enum15)$p),
						.Constant<System.RuntimeType>(System.Nullable`1[System.Int32]))
			}
		} .Else {
			null
		}
	}

it's from this code in our source:

     ConvertTo<int?>.From((Enum15?)null)

**Comment by dadhi** [comment]
@jogibear9988 

This fails?

```cs
ConvertTo<int?>.From((Enum15?)null)
```

or a switch expression above?

it would be good to have a complete expression or test.

**Comment by jogibear9988** [comment]
this fails, bit it creates the expression tree above, wich is compuled via fast expression compiler....
but there are more wich fail, but I need to look when I‘ve time to find out

**Comment by dadhi** [comment]
Ok, thanks for the info. I will come back to it when I complete hunting the gaps. 

Doing a lot of refactorings and cleanings lately. Hoping that some issues will be uncovered and fixed in the process.

**Comment by dadhi** [comment]
done in 7 months

**Pull request merged**
