### PR TITLE
Assignment support

### PR DESCRIPTION
**Pull request by z4kn4fein**
Hi @dadhi 

Sry for the latency, but here is the PR i promised about the Assignment support. I merged your already implemented version into mine, because i didn't covered the case when a passed parameter is being overridden, just that when a block's parameter is being set.

Thanks!

### CODE REVIEW

**Comment by dadhi** [comment]
Thanks for PR! I will review it a bit later.

**Comment by z4kn4fein** [comment]
Okay, i agree in that i should split the whole thing into smaller parts and discuss how it should behave first, to prevent digging into ways which are not meets some expectations.

This assignment part was a bit different from the original one which worked with blocks earlier, so i modified this a bit to just support the "assignment only" lambdas. I need some further work/investigation to cover both ways.

The simplest unit in my head regarding to the block support -which i got working earlier-, the simple block support without capturing local variables into nested lambdas. 

The nested lambda support could be the step after that, it's a bit trickier i think, we can discuss a bit more about it if you think.

So in the next few days i'll prepare the simple Block thingy if it's ok for you (sry in my hometown i don't have much time for coding :) ), trying to keep it in simple, maybe even in incomplete PRs, then let's see how to move forward. :)

Btw i have a "tmp" branch on my fork which is a kind of a playground of mine, there you can check what i'm currently playing with. There are some changes regarding to saving the generated il into a real assembly to check it with ilspy, just ignore that parts. :)

Thanks for the review!

**Comment by dadhi** [comment]
I will check the branch. I am not in haste to implement the Block, so take you time. Meanwhile I will commit whatever I have on my side regarding a Parameter plus your work on Member and tests.

**Comment by z4kn4fein** [comment]
Sure, ok, then i'm going to close this PR, and will open a new one for the Blocks

**Comment by dadhi** [comment]
I've pushed the changes, your tests and member assign with my cleanup are there.

**Pull request closed without merging**
