### PR TITLE
fixed coalesce ref

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**

### CODE REVIEW

**Comment by dadhi** [comment]
Is it on the master?

**Comment by dzmitry-lahoda** [comment]
master. I have started before dev related comment.

**Comment by dzmitry-lahoda** [comment]
i have rebased it on dev.

**Comment by dadhi** [comment]
Nice thank you.

**Comment by dadhi** [comment]
mmm, now I should merge all my changes with this PR. I don't get it Git :(

**Pull request merged**
