### PR TITLE
Improve the performance of variable lookup

### PR DESCRIPTION
**Pull request by ssupr**
This changes the variable lookup in the IsLocalVar and GetDefinedLocalVarOrDefault methods from an array loop to a dictionary key lookup.

We use Lamar in our project and there is a huge dependency tree that causes the CompileFast method to run on a BlockExpression containing up to 40,000 variable assignment expressions. That took about 35 sec to compile, but now it takes only 0.1 sec that significantly improved the performance of our project.

### CODE REVIEW

**Comment by dadhi** [comment]
@ssupr 

First, *40,000 variable assignment expressions.* ? This is great in terms of testing the project :) Could you share how is the part of this expression look like? Are there the dependency creation assignments for the specific dependency?

Second, Thanks for PR, I will review and try to incorporate the changes into the next bug-fix release.

**Comment by ssupr** [comment]
> @ssupr
> 
> First, _40,000 variable assignment expressions._ ? This is great in terms of testing the project :) Could you share how the part of this expression look like? Are there the dependency creation assignments for the specific dependency?

It looks like this:

................................
            var nullLogger21526 = new Edge.Core.Logging.NullLogger();
            var nullLogger21525 = new Edge.Core.Logging.NullLogger();
            var throwingDbFactory8021 = new Edge.Tests.ThrowingDbFactory();
            var t_EnumDataRepository374 = new Edge.Infrastructure.Repositories.Generated.T_EnumDataRepository(throwingDbFactory8021);
            var throwingDbFactory8013 = new Edge.Tests.ThrowingDbFactory();
            var databaseTypeProvider3246 = new Edge.Infrastructure.Repositories.Automatic.DatabaseTypeProvider();
            var t_ServiceDefLogRepository28 = new Edge.Infrastructure.Repositories.Generated.T_ServiceDefLogRepository(throwingDbFactory8013, databaseTypeProvider3246);
            var throwingDbFactory8014 = new Edge.Tests.ThrowingDbFactory();
            var databaseTypeProvider3247 = new Edge.Infrastructure.Repositories.Automatic.DatabaseTypeProvider();
            var t_ServiceDefLogRepository29 = new Edge.Infrastructure.Repositories.Generated.T_ServiceDefLogRepository(throwingDbFactory8014, databaseTypeProvider3247);
            var throwingDbFactory8015 = new Edge.Tests.ThrowingDbFactory();
            var t_ServiceDefPropertyRepository10 = new Edge.Infrastructure.Repositories.Generated.T_ServiceDefPropertyRepository(throwingDbFactory8015);
            var throwingDbFactory8016 = new Edge.Tests.ThrowingDbFactory();
            var t_EnumDataRepository370 = new Edge.Infrastructure.Repositories.Generated.T_EnumDataRepository(throwingDbFactory8016);
            var throwingDbFactory8017 = new Edge.Tests.ThrowingDbFactory();
            var t_EnumDataRepository371 = new Edge.Infrastructure.Repositories.Generated.T_EnumDataRepository(throwingDbFactory8017);
            var edgeEnumConverter179 = new Edge.Infrastructure.DomainRepositories.Enums.EdgeEnumConverter();
            var readOnlyRepository1231 = new Edge.Infrastructure.DomainRepositories.ReadOnlyRepository<Edge.Core.StronglyTyped.EnumValueName, Edge.Core.ValueTypes.EdgeEnum, Edge.Infrastructure.Repositories.Models.T_EnumData>(t_EnumDataRepository370, t_EnumDataRepository371, edgeEnumConverter179);
            var throwingDbFactory8018 = new Edge.Tests.ThrowingDbFactory();
            var t_EnumDataRepository372 = new Edge.Infrastructure.Repositories.Generated.T_EnumDataRepository(throwingDbFactory8018);
            var throwingDbFactory8019 = new Edge.Tests.ThrowingDbFactory();
            var t_EnumDataRepository373 = new Edge.Infrastructure.Repositories.Generated.T_EnumDataRepository(throwingDbFactory8019);
            var edgeEnumConverter180 = new Edge.Infrastructure.DomainRepositories.Enums.EdgeEnumConverter();
            var readOnlyRepository1232 = new Edge.Infrastructure.DomainRepositories.ReadOnlyRepository<Edge.Core.StronglyTyped.EnumValueId, Edge.Core.ValueTypes.EdgeEnum, Edge.Infrastructure.Repositories.Models.T_EnumData>(t_EnumDataRepository372, t_EnumDataRepository373, edgeEnumConverter180);
            var inline_instantMapper80 = new Edge.Infrastructure.InstantMapper();
            var dynamicTablePropertyDataConverter80 = new Edge.Infrastructure.Converters.DynamicTablePropertyDataConverter(readOnlyRepository1231, readOnlyRepository1232, inline_instantMapper80);
            var inline_defaultValueConverter56 = new Edge.Infrastructure.DomainRepositories.DynamicTables.DefaultValueConverter(dynamicTablePropertyDataConverter80);
            var serviceDefinitionPropertyDefinitionFromDbConverter10 = new Edge.Infrastructure.DomainRepositories.Products.Converters.ServiceDefinitionPropertyDefinitionFromDbConverter(inline_defaultValueConverter56);
            var serviceDefinitionDynamicTableDefinitionRepository10 = new Edge.Infrastructure.DomainRepositories.Products.ServiceDefinitionDynamicTableDefinitionRepository(t_ServiceDefPropertyRepository10, serviceDefinitionPropertyDefinitionFromDbConverter10);
            var throwingDbFactory8020 = new Edge.Tests.ThrowingDbFactory();
            var databaseTypeProvider3248 = new Edge.Infrastructure.Repositories.Automatic.DatabaseTypeProvider();
................................................

**Comment by ssupr** [comment]
The code above is a part of Lamar's HowDoIBuild method output.

**Comment by dadhi** [comment]
@ssupr Thanks, interesting. So you build the output of the diagnostic method? 
Just curious, is it supposed to be like this or Lamar does the same thing internally?

**Comment by ssupr** [comment]
Lamar compiles ParameterExpression list as BlockExpression
------------------------
            var variables = _variables.Values.OfType<ParameterExpression>().Where(x => x.Name != "scope");
            var body = Expression.Block(variables, Body);
            var lambda = Expression.Lambda<TFunc>(body, Arguments);

            return lambda.CompileFast<TFunc>();
-----------------------
That code is only visualisation for diagnostic purposes.

**Comment by dadhi** [comment]
Ok, got it.

**Comment by dadhi** [comment]
@ssupr Ok, I am gonna merge the PR and play with integrated change
because I have some doubts about performance regressions for other cases.

**Comment by ssupr** [comment]
Thank you!

**Pull request merged**
