### PR TITLE
added broken ref tests

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**

### CODE REVIEW

**Comment by dadhi** [comment]
> should we support wrong trees as LINQ does that?

Likely, yes. Also because of perf reasons. The rule is simple, we can check whatever if it is free performance-wise.

**Comment by dadhi** [comment]
I will check `what??? no chance` later

**Comment by dzmitry-lahoda** [comment]
>> Likely, yes. Also because of perf reasons. The rule is simple, we can check whatever if it is free performance-wise.

Or may be create issue for each wrong tree and wait for vote to fix?

**Comment by dadhi** [comment]
Just wait for decent PR with the fix and no performance regression, from whoever is interested in particular scenario.

**Pull request merged**
