### PR TITLE
Fix bug in ToExpressionString with lifted binary expressions

### PR DESCRIPTION
**Pull request by exyi**
I encountered this bug when looking for other problems.

I also slightly improved the constant's ToCode:
* there was a duplicated check if it's possible to write the constant, so I moved it to one place. This fixes a problem that it could not print `Nullable<int>` which was quite annoying.
* typeof(Nullable<int>) is now printed as typeof(int?)
* `(int)1` is unnecessary, so now it will print just `1`
* basic support for DateTime, TimeSpan, Guid constants
* `new LabelTarget[0]` and similar are not part of the output unless it's required. it just makes it less intimidating to me :sweat_smile:

### CODE REVIEW

**Comment by dadhi** [comment]
Great again. The expression output is useful and I happy that someone except looking at it. At the moment one of the tests is failing - it is checking the output.
I wonder how do you run the tests and build locally or did I ever mentioned the process in the docs. I usually just run `b.but` to quickly check that all is passing.

**Comment by exyi** [comment]
> The expression output is useful and I happy that someone except me is looking at it

It's super useful, if only I knew about this library earlier :sweat_smile: 


> At the moment one of the tests is failing - it is checking the output.

Yea, I noticed that, it's probably due to another bug with LiftToNull in LightExpressions. I don't know how to fix it atm, I'll have to look more into that.

>  I wonder how do you run the tests and build locally or did I ever mentioned the process in the docs. I usually just run b.bat to quickly check that all is passing.

Just `dotnet test`. I'm working on Linux, so batfile won't work anyway

**Comment by dadhi** [comment]
@exyi Got it. I am fixing somth related now for #309.

Regarding Linux, I will look how scripts are organized - the one of the points of my own test runners programs was to avoid libs (nunit and xunit) slowleness, and moreover the unexplained dead stops locally and on CI.  So you may just `dotnet run <testrunner.csproj>`.
Another point was for debugging the tests by just F5 for case when OmniSharp (VSCode) was failing to recognize the tests for some reason and no longer providing the run/debug lens on them.

**Comment by dadhi** [comment]
@exyi 

yep , for Linux and Mac I have just
```
dotnet run  -f netcoreapp3.1 -c Release -p test/FastExpressionCompiler.TestsRunner/FastExpressionCompiler.TestsRunner.csproj
```

**Comment by dadhi** [comment]
@exyi I will merge the PR in the current state and fix the test myself to speed-up things.

**Comment by exyi** [comment]
Thanks! I could not figure this one out.

**Pull request merged**
